[workspace]
authors = ["Harish Naik <harishgnaik@gmail.com>"]
channels = ["conda-forge"]
name = "cpp-project-tmpl"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[tasks.config]
cmd = [
    "cmake", "-G", "Ninja", "-S", ".", "-B", "build/debug",
    "-DCMAKE_BUILD_TYPE=Debug"]

[dependencies]
gcc = ">=15.2.0,<15.3"
gxx = ">=15.2.0,<15.3"
cmake = ">=4.2.3,<5"
clang-format = ">=21.1.8,<22"
clang-tools = ">=21.1.8,<22"
catch2 = ">=3.12.0,<4"
boost = ">=1.85.0,<2"
